参考文章：https://juejin.cn/post/6844903869407985672#heading-0

1. 将异步问题变同步，避免多级嵌套。在此之前，为了获取异步的调用结果，不得不使用大量的回调。当多个异步请求需要相互依赖时，只能通过嵌套的方式解决。这种编码方式存在的问题：

   - 代码臃肿。

   - 可读性差。

   - 耦合度过高，可维护性差。

   - 代码复用性差。

   - 容易滋生 bug。

   - 只能在回调里处理异常。

2. Promise 是异步编程的一种解决方案，比传统的异步解决方案【回调函数】和【事件】更合理、更强大。

   - 从语法上讲，promise 是一个对象，从它可以获取异步操作的消息

   - 从本意上讲，它是承诺，承诺它过一段时间会给你一个结果

3. 三个状态：pending未完成状态 fulfilled完成状态 rejected失败状态。只能从pending状态转到resolve或rejected状态

4. Promise 是一个构造函数，使用 new 操作符返回一个 promise 对象

5. Promise对象上的方法

   - then方法：接收终值

     promise.then(onFulfilled,onRejected)

     - onFulfilled 函数用于当 promise 状态变为 fulfilled 时，接收终值
     - onRejected 函数用于当 promise 状态变为 rejected 时，接收拒因

     ##### onFulfilled 和 onRejected 的调用时机

     - 当 promise 对象的状态变为 fulfilled 或 rejected 时调用
     - onFulfilled、onRejected 永远都是异步调用
     - onFulfilled、onRejected 在事件队列中作为微任务来处理

     ##### onFulfilled 和 onRejected 的调用要求

     - onFulfilled 和 onRejected 必须被作为函数调用
     - 非严格模式下，this 为全局对象
     - 严格模式下，this 为 undefined

     ##### then方法的多次调用

     - then 方法可以被同一个 promise 对象多次调用

     - then 方法会返回一个新的 promise 对象

     - 当 promise 成功执行时，所有 onFulfilled 需按照其注册顺序依次回调

     - 当 promise 被拒绝执行时，所有的 onRejected 需按照其注册顺序依次回调

     ##### then方法的返回值 :返回的是一个promise对象

   - catch方法：接收拒因

     - catch(fn) 方法实际上是 then(null,fn) 方法的别名，catch 方法的返回值以及 catch 方法中出现异常的情况与调用 then 方法相同

       ```
       new Promise((resolve,reject)=>{
           reject()
       }).then(null,function(error){
       
       })
       // 等同于
       new Promise((resolve,reject)=>{
           reject()
       }).catch(function(error){
       
       })
       ```

       

6. Promise的静态方法

- ##### Promise.resolve

  ```
  let p = Promise.resolve(x)
  // 等价于
  let p = new Promise((resolve)=>{
      resolve(x)
  })
  ```

- ##### Promise.reject

  ```
  let p = Promise.reject(x)
  // 等价于
  let p = new Promise((resolve,reject)=>{
      reject(x)
  })
  ```

  #### Promise.all

  - Promise.all 方法用于将多个 promise 对象包装成一个新的 promise 对象

  ```
  const p = Promise.all([p1, p2, p3]);
  复制代码
  ```

  - p1、p2、p3 都是 promise 对象，如果不是，调用 Promise.resolve 方法转换为 promise 对象
  - p 的状态由 p1、p2、p3 决定
    - 当 p1、p2、p3 的状态都变成 fulfilled
      - p 的状态为 fulfilled
      - 此时 p1、p2、p3 的终值组成一个数组，这个数组作为 p 的终值
    - 当 p1、p2、p3 的状态有一个变成 rejected
      - p 的状态变为 rejected
      - 此时第一个状态变为 rejected 的 promise 对象的拒因作为 p 的拒因

#### Promise.race

- Promise.race 方法同样用于将多个 promise 对象包装成一个新的 promise 对象

```
const p = Promise.race([p1, p2, p3]);
复制代码
```

- p1、p2、p3 都是 promise 对象，如果不是，调用 Promise.resolve 方法转换为 promise 对象
- p 的状态由 p1、p2、p3 中状态最先变为 fulfilled 或 rejected 的 promise 对象决定
- p 的终值或拒因由最先变更状态的 promise 对象所决定

## Promise 的错误捕获

当 promise 的状态为 rejected 且为对 promise 对象使用 catch 方法，此时的异常信息会被 promise 对象吃掉 可以通过监听 unhandledRejection 事件，专门监听未捕获的reject错误

```
// node 环境下
process.on('unhandledRejection', error => {
    console.log('unhandledRejection', error);
});
// 浏览器下
window.addEventListener('unhandledrejection',(e)=>{
    e.preventDefault();
    console.log(e);
});
```

## Promise 的问题

- 无法取消Promise，若没有状态变更，也无法停止 promise 的等待
- 不设定 then 或 catch 方法，构造函数(excutor函数)错误，无法捕获
- 未完成状态时，无法得知是刚开始，还是即将完成